projects:
  gql:
    schemaPath: amplify/backend/api/gql/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/graphql/API.ts
        docsFilePath: src/graphql
        maxDepth: 4
extensions:
  amplify:
    version: 3
